// adams_dungeon.res - created with RESGen v2.0 RC2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (loads):
adams_dungeon.wad
halflife.wad
liquids.wad
gfx/env/cm-thosemntns256_bk.bmp
gfx/env/cm-thosemntns256_bk.tga
gfx/env/cm-thosemntns256_dn.bmp
gfx/env/cm-thosemntns256_dn.tga
gfx/env/cm-thosemntns256_ft.bmp
gfx/env/cm-thosemntns256_ft.tga
gfx/env/cm-thosemntns256_lf.bmp
gfx/env/cm-thosemntns256_lf.tga
gfx/env/cm-thosemntns256_rt.bmp
gfx/env/cm-thosemntns256_rt.tga
gfx/env/cm-thosemntns256_up.bmp
gfx/env/cm-thosemntns256_up.tga
gfx/env/cm-thosemntns.txt
maps/adams_dungeon.cfg
maps/adams_dungeon.txt
maps/adams_dungeon_motd.txt
maps/adams_dungeon_skl.cfg
models/adamr/bird.mdl
models/adamr/bush.mdl
models/adamr/tree.mdl
models/adamr/treestump.mdl
models/adamr/vase.mdl
models/gib_skull.mdl
models/skeleton.mdl
sound/adamr/boss_create.wav
sound/adamr/boss_defeated.wav
sound/adamr/buttons_sync.wav
sound/adamr/candle.wav
sound/adamr/healing_spring.wav
sound/adamr/lava.wav
sound/adamr/music/aroundtheworld.wav
sound/adamr/music/daloop3.wav
sound/adamr/music/daloop4.wav
sound/adamr/music/daloop6.wav
sound/adamr/music/popcorn.wav
sound/adamr/music/seeyouinhell.wav
sound/adamr/music/stepup.wav
sound/adamr/music/timeisnow.wav
sound/adamr/music/whatislove.wav
sound/adamr/music/zombienation.wav
sound/adamr/player_eaten.wav
sound/adamr/waterfall.wav
sound/adamr/waterfountain.wav
sound/adamr/wind.wav
sound/ambience/alien_squit.wav
sound/ambience/flameburst1.wav
sound/ambience/quail1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/siren.wav
sound/ambience/steamjet1.wav
sound/ambience/the_horror1.wav
sound/ambience/the_horror2.wav
sound/ambience/the_horror3.wav
sound/ambience/the_horror4.wav
sound/ambience/wren1.wav
sound/weapons/electro4.wav
sound/weapons/mine_deploy.wav
sound/weapons/xbow_hit2.wav
sprites/adamr/smokepuff.spr
sprites/enter1.spr
sprites/exit1.spr
sprites/fexplo.spr
sprites/fire.spr
sprites/laserbeam.spr
sprites/smoke.spr
