maps/escape_series_3d.cfg
maps/escape_series_3d.res
maps/escape_series_3d_motd.txt
sound/escape_series_3d/barney.txt
sound/escape_series/barney/escape_barney_1.wav
sound/escape_series/barney/escape_barney_2.wav
sound/escape_series/barney/escape_barney_3.wav
sound/escape_series/barney/escape_barney_4.wav
sound/escape_series/barney/escape_barney_5.wav
sound/escape_series/barney/escape_barney_6.wav
sound/escape_series/barney/escape_barney_7.wav
sound/escape_series/barney/escape_barney_8.wav
sound/escape_series/barney/escape_barney_9.wav
