// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/d1e3skybk.tga
gfx/env/d1e3skydn.tga
gfx/env/d1e3skyft.tga
gfx/env/d1e3skylf.tga
gfx/env/d1e3skyrt.tga
gfx/env/d1e3skyup.tga
hellmouth.wad
models/hellmouth/agrunt.mdl
models/hellmouth/agrunt01.mdl
models/hellmouth/angelchubstat_HUGE.mdl
models/hellmouth/big_mom.mdl
models/hellmouth/big_momT.mdl
models/hellmouth/controller.mdl
models/hellmouth/controllerT.mdl
models/hellmouth/gonome.mdl
models/hellmouth/HgruntDead.mdl
models/hellmouth/hungerslave.mdl
models/hellmouth/hungerslave01.mdl
models/hellmouth/hungerslave02.mdl
models/hellmouth/hungerslavehell.mdl
models/hellmouth/hungerslavet.mdl
models/hellmouth/hungerzork.mdl
models/hellmouth/hungerzork01.mdl
models/hellmouth/hungerzorkt.mdl
models/hellmouth/panther.mdl
models/hellmouth/puppeh.mdl
models/hellmouth/zombie.mdl
models/hellmouth/zombie01.mdl
models/hellmouth/zombie02.mdl
models/hellmouth/zombie03.mdl
models/hellmouth/zombie_barney.mdl
models/hellmouth/zombie_soldier.mdl
sound/hellmouth/spawn.wav
sound/hellmouth/spawn2.wav
sound/hungerslave/slv_alert1.wav
sound/hungerslave/slv_alert3.wav
sound/hungerslave/slv_alert4.wav
sound/hungerslave/slv_die2.wav
sound/hungerslave/slv_pain1.wav
sound/hungerslave/slv_pain2.wav
sound/hungerslave/slv_word1.wav
sound/hungerslave/slv_word2.wav
sound/hungerslave/slv_word3.wav
sound/hungerslave/slv_word4.wav
sound/hungerslave/slv_word5.wav
sound/hungerslave/slv_word6.wav
sound/hungerslave/slv_word7.wav
sound/hungerslave/slv_word8.wav
sound/hungerzork/ag_alert1.wav
sound/hungerzork/ag_alert2.wav
sound/hungerzork/ag_alert3.wav
sound/hungerzork/ag_alert4.wav
sound/hungerzork/ag_alert5.wav
sound/hungerzork/ag_attack1.wav
sound/hungerzork/ag_attack2.wav
sound/hungerzork/ag_attack3.wav
sound/hungerzork/ag_die1.wav
sound/hungerzork/ag_die2.wav
sound/hungerzork/ag_die3.wav
sound/hungerzork/ag_die4.wav
sound/hungerzork/ag_die5.wav
sound/hungerzork/ag_idle1.wav
sound/hungerzork/ag_idle2.wav
sound/hungerzork/ag_idle3.wav
sound/hungerzork/ag_idle4.wav
sound/hungerzork/ag_idle5.wav
sound/hungerzork/ag_pain1.wav
sound/hungerzork/ag_pain2.wav
sound/hungerzork/ag_pain3.wav
sound/hungerzork/ag_pain4.wav
sound/hungerzork/ag_pain5.wav
sound/hungerzork/leftfoot2.wav
sound/hungerzork/leftfoot4.wav
sound/hungerzork/rightfoot1.wav
sound/hungerzork/rightfoot3.wav
sound/panther/p_alert1.wav
sound/panther/p_alert2.wav
sound/panther/p_alert3.wav
sound/panther/p_die1.wav
sound/panther/p_die2.wav
sound/panther/p_idle1.wav
sound/panther/p_idle2.wav
sound/panther/p_idle3.wav
sound/panther/p_pain1.wav
sound/panther/p_pain2.wav
sound/panther/p_zap1.wav
sound/panther/p_zap2.wav
sound/panther/pclaw_miss1.wav
sound/panther/pclaw_miss2.wav
sound/panther/pclaw_strike1.wav
sound/panther/pclaw_strike2.wav
sound/panther/pclaw_strike3.wav
