// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/fullmoonbk.tga
gfx/env/fullmoondn.tga
gfx/env/fullmoonft.tga
gfx/env/fullmoonlf.tga
gfx/env/fullmoonrt.tga
gfx/env/fullmoonup.tga
models/afrikakorps/misc/gascan.mdl
models/aomdc/barnacle.mdl
models/aomdc/bullchicken.mdl
models/aomnewweapons2/p_shotgun.mdl
models/aomnewweapons2/svenhands/v_shotgun.mdl
models/aomnewweapons2/w_shotgun.mdl
models/bushes/bigbush.mdl
models/hunger/svenhands/p_2uzis.mdl
models/hunger/svenhands/p_2uzis_gold.mdl
models/hunger/svenhands/p_hunger9mmar.mdl
models/hunger/svenhands/p_hunger9mmhandgun.mdl
models/hunger/svenhands/p_hungercrossbow.mdl
models/hunger/svenhands/p_hungersatchel.mdl
models/hunger/svenhands/p_hungersatchel_radio.mdl
models/hunger/svenhands/p_hungershotgun.mdl
models/hunger/svenhands/p_m40a1.mdl
models/hunger/svenhands/p_rpg.mdl
models/hunger/svenhands/p_uzi.mdl
models/hunger/svenhands/p_uzi_gold.mdl
models/hunger/svenhands/rpgrocket.mdl
models/hunger/svenhands/v_hunger357.mdl
models/hunger/svenhands/v_hunger9mmar.mdl
models/hunger/svenhands/v_hunger9mmhandgun.mdl
models/hunger/svenhands/v_hungercrossbow.mdl
models/hunger/svenhands/v_hungersatchel.mdl
models/hunger/svenhands/v_hungersatchel_radio.mdl
models/hunger/svenhands/v_hungershotgun.mdl
models/hunger/svenhands/v_m40a1.mdl
models/hunger/svenhands/v_rpg.mdl
models/hunger/svenhands/v_tnt.mdl
models/hunger/svenhands/v_uzi.mdl
models/hunger/svenhands/w_2uzis.mdl
models/hunger/svenhands/w_2uzis_gold.mdl
models/hunger/svenhands/w_hunger9mmar.mdl
models/hunger/svenhands/w_hunger9mmhandgun.mdl
models/hunger/svenhands/w_hungercrossbow.mdl
models/hunger/svenhands/w_hungersatchel.mdl
models/hunger/svenhands/w_hungershotgun.mdl
models/hunger/svenhands/w_m40a1.mdl
models/hunger/svenhands/w_rpg.mdl
models/hunger/svenhands/w_rpgammo.mdl
models/hunger/svenhands/w_uzi.mdl
models/hunger/svenhands/w_uzi_gold.mdl
models/keen/delta.mdl
models/keen/p_greenmp5.mdl
models/keen/v_greenmp5.mdl
models/keen/w_greenmp5.mdl
models/keenhalloween/cryokeen.mdl
models/keenhalloween/g1l/fixed/big_mom.mdl
models/keenhalloween/p_firehose.mdl
models/keenhalloween/p_medkit.mdl
models/keenhalloween/pumpkin2.mdl
models/keenhalloween/pumpkinsnark.mdl
models/keenhalloween/v_firehose.mdl
models/keenhalloween/v_medkit.mdl
models/keenhalloween/v_pumpkin.mdl
models/keenhalloween/w_firehose.mdl
models/keenhalloween/w_pmedkit.mdl
models/opfor/svenhands/v_knife.mdl
models/oxyhalloween/p_bgrap.mdl
models/oxyhalloween/p_rustybloodm16.mdl
models/oxyhalloween/v_bgrap_fixed.mdl
models/oxyhalloween/v_bgraptip.mdl
models/oxyhalloween/v_rustybloodm16.mdl
models/oxyhalloween/w_bgrap.mdl
models/oxyhalloween/w_rustybloodm16.mdl
models/peany/picard_v2.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/icky.mdl
models/sc_activist/ickyT.mdl
models/sectore/darkdrone3.mdl
models/turr/p_keyboard_v2.mdl
models/turr/v_keyboard_v2.mdl
models/turr/w_keyboard_v2.mdl
sound/aomlowercase/barnacle/bcl_alert2.wav
sound/aomlowercase/barnacle/bcl_bite3.wav
sound/aomlowercase/barnacle/bcl_die1.wav
sound/aomlowercase/barnacle/bcl_die3.wav
sound/aomlowercase/barnacle/bcl_tongue1.wav
sound/aomlowercase/bullchicken/bc_acid1.wav
sound/aomlowercase/bullchicken/bc_acid2.wav
sound/aomlowercase/bullchicken/bc_attack1.wav
sound/aomlowercase/bullchicken/bc_attack2.wav
sound/aomlowercase/bullchicken/bc_attack3.wav
sound/aomlowercase/bullchicken/bc_attackgrowl.wav
sound/aomlowercase/bullchicken/bc_attackgrowl2.wav
sound/aomlowercase/bullchicken/bc_attackgrowl3.wav
sound/aomlowercase/bullchicken/bc_bite1.wav
sound/aomlowercase/bullchicken/bc_bite2.wav
sound/aomlowercase/bullchicken/bc_bite3.wav
sound/aomlowercase/bullchicken/bc_die1.wav
sound/aomlowercase/bullchicken/bc_die2.wav
sound/aomlowercase/bullchicken/bc_die3.wav
sound/aomlowercase/bullchicken/bc_idle1.wav
sound/aomlowercase/bullchicken/bc_idle2.wav
sound/aomlowercase/bullchicken/bc_idle3.wav
sound/aomlowercase/bullchicken/bc_idle4.wav
sound/aomlowercase/bullchicken/bc_idle5.wav
sound/aomlowercase/bullchicken/bc_pain1.wav
sound/aomlowercase/bullchicken/bc_pain2.wav
sound/aomlowercase/bullchicken/bc_pain3.wav
sound/aomlowercase/bullchicken/bc_pain4.wav
sound/aomlowercase/bullchicken/bc_spithit1.wav
sound/aomlowercase/bullchicken/bc_spithit2.wav
sound/aomlowercase/bullchicken/bc_spithit3.wav
sound/aomlowercase/houndeye/he_alert1.wav
sound/aomlowercase/houndeye/he_alert2.wav
sound/aomlowercase/houndeye/he_alert3.wav
sound/aomlowercase/houndeye/he_attack1.wav
sound/aomlowercase/houndeye/he_attack2.wav
sound/aomlowercase/houndeye/he_attack3.wav
sound/aomlowercase/houndeye/he_blast1.wav
sound/aomlowercase/houndeye/he_blast2.wav
sound/aomlowercase/houndeye/he_blast3.wav
sound/aomlowercase/houndeye/he_die1.wav
sound/aomlowercase/houndeye/he_die2.wav
sound/aomlowercase/houndeye/he_die3.wav
sound/aomlowercase/houndeye/he_hunt1.wav
sound/aomlowercase/houndeye/he_hunt2.wav
sound/aomlowercase/houndeye/he_hunt3.wav
sound/aomlowercase/houndeye/he_hunt4.wav
sound/aomlowercase/houndeye/he_idle1.wav
sound/aomlowercase/houndeye/he_pain1.wav
sound/aomlowercase/houndeye/he_pain2.wav
sound/aomlowercase/houndeye/he_pain3.wav
sound/aomlowercase/houndeye/he_pain4.wav
sound/aomlowercase/houndeye/he_pain5.wav
sound/bluecell/resurrecttarget.wav
sound/classic/Items/9mmclip1.wav
sound/keen/cg_rdmtrain01.wav
sound/keen/locksmith.wav
sound/keenhalloween/bam.wav
sound/keenhalloween/bravest.wav
sound/keenhalloween/dialogs/kh3/findkeen.ogg
sound/keenhalloween/forcefield.wav
sound/keenhalloween/g1l/atmosfera2.mp3
sound/keenhalloween/g1l/combate1.mp3
sound/keenhalloween/g1l/doormv1.wav
sound/keenhalloween/g1l/laser.wav
sound/keenhalloween/g1l/trancetrack1.ogg
sound/keenhalloween/g1l/trancetrack2.ogg
sound/keenhalloween/hks1.wav
sound/keenhalloween/picard_hello.wav
sound/keenhalloween/picardspeech.wav
sound/keenhalloween/riker-eating_gagh.wav
sound/keenhalloween/touch.wav
sound/keenhalloween/waterblast.wav
sound/keenhalloween/watercannonoff.wav
sound/keenhalloween/watercannonon.wav
sound/keenrpg/cinema.wav
sound/keenrpg/doorgrunt.wav
sound/keenrpg/getiem2.wav
sound/keenrpg/getitem.wav
sound/keenrpg/getitem2.wav
sound/keenrpg/globglob.wav
sound/sc_frogger/secret.wav
sound/sectore/pit_drone_alert1.wav
sound/sectore/pit_drone_alert2.wav
sound/sectore/pit_drone_alert3.wav
sound/sectore/pit_drone_attack_spike1.wav
sound/sectore/pit_drone_attack_spike2.wav
sound/sectore/pit_drone_communicate1.wav
sound/sectore/pit_drone_communicate2.wav
sound/sectore/pit_drone_communicate3.wav
sound/sectore/pit_drone_communicate4.wav
sound/sectore/pit_drone_die1.wav
sound/sectore/pit_drone_die2.wav
sound/sectore/pit_drone_die3.wav
sound/sectore/pit_drone_eat.wav
sound/sectore/pit_drone_hunt1.wav
sound/sectore/pit_drone_hunt2.wav
sound/sectore/pit_drone_hunt3.wav
sound/sectore/pit_drone_idle1.wav
sound/sectore/pit_drone_idle2.wav
sound/sectore/pit_drone_idle3.wav
sound/sectore/pit_drone_melee_attack1.wav
sound/sectore/pit_drone_melee_attack2.wav
sound/sectore/pit_drone_pain1.wav
sound/sectore/pit_drone_pain2.wav
sound/sectore/pit_drone_pain3.wav
sound/sectore/pit_drone_pain4.wav
sound/tur/coin.wav
sound/tur/dipper.wav
sound/tur/hongkong3.wav
sound/tur/nash.wav
sound/w00tguy/arcade/pong_hit.wav
sound/w00tguy/arcade/pong_join.wav
sound/w00tguy/arcade/pong_quit.wav
sound/w00tguy/arcade/pong_score.wav
sound/w00tguy/arcade/pong_start.wav
sound/w00tguy/arcade/pong_win.wav
sound/weapons/1911meu/MagIn.wav
sound/weapons/1911meu/MagOut.wav
sound/weapons/1911meu/SlidePull.wav
sound/weapons/1911meu/SlideRelease.wav
sound/weapons/knife_deploy1.wav
sound/weapons/Skorpion/Fire_Both1.wav
sound/weapons/Skorpion/Shoot1.wav
sound/weapons/Skorpion/Skr_Cock.wav
sound/weapons/Skorpion/Skr_Magin.wav
sound/weapons/Skorpion/Skr_Magout.wav
sprites/face4.spr
sprites/face6.spr
sprites/face7.spr
sprites/keenhalloween/flames2.spr
sprites/keenhalloween/picardcoin.spr
sprites/rolleyes.spr
sprites/w00tguy/arcade/numbers.spr
sprites/w00tguy/arcade/pong.spr
