maps/otokotati_no_kouzan.cfg
maps/otokotati_no_kouzan_motd.txt
maps/otokotati_no_kouzan_skl.cfg
models/otokotati_no_kouzan/bentou.mdl
models/otokotati_no_kouzan/bentout.mdl
models/otokotati_no_kouzan/helmet.mdl
models/otokotati_no_kouzan/helmett.mdl
models/otokotati_no_kouzan/model.txt
models/otokotati_no_kouzan/p_357.mdl
models/otokotati_no_kouzan/p_crowbar.mdl
models/otokotati_no_kouzan/p_desert_eagle.mdl
models/otokotati_no_kouzan/p_grenade.mdl
models/otokotati_no_kouzan/p_medkit.mdl
models/otokotati_no_kouzan/p_pipe_wrench.mdl
models/otokotati_no_kouzan/p_rpg.mdl
models/otokotati_no_kouzan/p_rpg_r.mdl
models/otokotati_no_kouzan/p_satchel.mdl
models/otokotati_no_kouzan/p_satchel_radio.mdl
models/otokotati_no_kouzan/p_shotgun.mdl
models/otokotati_no_kouzan/p_squeak.mdl
models/otokotati_no_kouzan/p_tripmine.mdl
models/otokotati_no_kouzan/rpgrocket.mdl
models/otokotati_no_kouzan/v_357.mdl
models/otokotati_no_kouzan/v_crowbar.mdl
models/otokotati_no_kouzan/v_desert_eagle.mdl
models/otokotati_no_kouzan/v_grenade.mdl
models/otokotati_no_kouzan/v_medkit.mdl
models/otokotati_no_kouzan/v_pipe_wrench.mdl
models/otokotati_no_kouzan/v_rpg.mdl
models/otokotati_no_kouzan/v_satchel.mdl
models/otokotati_no_kouzan/v_satchel_radio.mdl
models/otokotati_no_kouzan/v_shotgun.mdl
models/otokotati_no_kouzan/v_squeak.mdl
models/otokotati_no_kouzan/v_tripmine.mdl
models/otokotati_no_kouzan/w_357.mdl
models/otokotati_no_kouzan/w_crowbar.mdl
models/otokotati_no_kouzan/w_crowbart.mdl
models/otokotati_no_kouzan/w_desert_eagle.mdl
models/otokotati_no_kouzan/w_grenade.mdl
models/otokotati_no_kouzan/w_grenadet.mdl
models/otokotati_no_kouzan/w_pipe_wrench.mdl
models/otokotati_no_kouzan/w_pmedkit.mdl
models/otokotati_no_kouzan/w_rpgammo.mdl
models/otokotati_no_kouzan/w_rpg.mdl
models/otokotati_no_kouzan/w_satchel.mdl
models/otokotati_no_kouzan/w_shotgun.mdl
models/otokotati_no_kouzan/w_sqknest.mdl
models/otokotati_no_kouzan/w_squeak.mdl
models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/uboa/iwao.mdl
sound/otokotati_no_kouzan/chijonohosi.wav
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
