// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/richard_boderman/boderman.mdl
models/richard_boderman/bulb.mdl
models/richard_boderman/Hassassin.mdl
models/richard_boderman/palm1.mdl
models/richard_boderman/palm2.mdl
models/richard_boderman/palm3.mdl
models/richard_boderman/plant.mdl
models/scmod/npcs/barnotis/captainscarlet.mdl
models/scmod/npcs/barnotis/commando.mdl
models/scmod/npcs/barnotis/dan200.mdl
models/scmod/npcs/barnotis/elgringo.mdl
models/scmod/npcs/barnotis/evilpentapenguin.mdl
models/scmod/npcs/barnotis/fieldmedic.mdl
models/scmod/npcs/barnotis/law_and_order.mdl
models/scmod/npcs/barnotis/nev.mdl
models/scmod/npcs/barnotis/offwhitepenguin.mdl
models/scmod/npcs/barnotis/policelt.mdl
models/scmod/npcs/barnotis/saff.mdl
models/scmod/npcs/barnotis/slidje.mdl
models/scmod/npcs/barnotis/svenviking.mdl
models/scmod/npcs/barnotis/the-real-game.mdl
models/scmod/npcs/bbgarg/hellsflame.mdl
models/scmod/npcs/fassn/bluefeena.mdl
models/scmod/npcs/fassn/hezus.mdl
models/scmod/npcs/fassn/zpelmo.mdl
models/scmod/npcs/garg/jusupov.mdl
models/scmod/npcs/garg/picklehead.mdl
models/scmod/npcs/hc/dizney.mdl
models/scmod/npcs/hc/edcrab.mdl
models/scmod/npcs/hc/incy247.mdl
models/scmod/npcs/hgrunt/civilian_soldier.mdl
models/scmod/npcs/hgrunt/film11.mdl
models/scmod/npcs/hgrunt/garompa.mdl
models/scmod/npcs/hgrunt/hell-met.mdl
models/scmod/npcs/hgrunt/hydeph.mdl
models/scmod/npcs/hgrunt/mikker.mdl
models/scmod/npcs/hgrunt/moving_sulphur.mdl
models/scmod/npcs/hgrunt/nih_red.mdl
models/scmod/npcs/hwgr/madjonesy.mdl
models/scmod/npcs/hwgr/mgwedd.mdl
models/scmod/npcs/hwgr/omega.mdl
models/scmod/npcs/islave/lurid.mdl
models/scmod/npcs/massn/a1win.mdl
models/scmod/npcs/massn/bruk.mdl
models/scmod/npcs/massn/captain_falcon.mdl
models/scmod/npcs/massn/dred_furst.mdl
models/scmod/npcs/massn/ichii3D.mdl
models/scmod/npcs/massn/lento.mdl
models/scmod/npcs/massn/moorhsum.mdl
models/scmod/npcs/massn/mutantmfm.mdl
models/scmod/npcs/massn/panzerfaust.mdl
models/scmod/npcs/massn/pd-kc.mdl
models/scmod/npcs/massn/sharkman.mdl
models/scmod/npcs/massn/sniper.mdl
models/scmod/npcs/massn/synchro.mdl
models/scmod/npcs/massn/venom.mdl
models/scmod/npcs/massn/wildcat_za.mdl
models/scmod/npcs/massn/wolf-kain.mdl
models/scmod/npcs/op4/daza400.mdl
models/scmod/npcs/op4/felix.mdl
models/scmod/npcs/op4/fragrag.mdl
models/scmod/npcs/op4/kuroneko.mdl
models/scmod/npcs/op4/nivekdev.mdl
models/scmod/npcs/op4/rangersix.mdl
models/scmod/npcs/rgrunt/60mbbot.mdl
models/scmod/npcs/rgrunt/aurora.mdl
models/scmod/npcs/rgrunt/evil.mdl
models/scmod/npcs/rgrunt/programzeta.mdl
models/scmod/npcs/rgrunt/turrican.mdl
models/scmod/npcs/rgrunt/tweak.mdl
models/scmod/npcs/strooper/jpolito_old.mdl
models/scmod/npcs/strooper/viger.mdl
models/scmod/npcs/zombie/rebecca.mdl
models/scmod/npcs/zombie/wolf.mdl
sound/barniel/aimforhead.wav
sound/barniel/badfeeling.wav
sound/barniel/bequiet.wav
sound/barniel/bn_another.wav
sound/barniel/bn_attack1.wav
sound/barniel/bn_becarefull.wav
sound/barniel/bn_bring.wav
sound/barniel/bn_carefull.wav
sound/barniel/bn_close.wav
sound/barniel/bn_die1.wav
sound/barniel/bn_dontdothat.wav
sound/barniel/bn_dontmake.wav
sound/barniel/bn_endline.wav
sound/barniel/bn_firepl.wav
sound/barniel/bn_friends.wav
sound/barniel/bn_gotone.wav
sound/barniel/bn_onelessh.wav
sound/barniel/bn_pain1.wav
sound/barniel/bn_pain2.wav
sound/barniel/bn_seethat.wav
sound/barniel/bn_stepoff.wav
sound/barniel/bn_tomb.wav
sound/barniel/bn_whatyou.wav
sound/barniel/diegreenthing.wav
sound/barniel/dontagree.wav
sound/barniel/dontknow.wav
sound/barniel/drinktopside.wav
sound/barniel/hearsomething.wav
sound/barniel/hevno.wav
sound/barniel/hi.wav
sound/barniel/hitbad.wav
sound/barniel/hoyes.wav
sound/barniel/humm.wav
sound/barniel/imhit.wav
sound/barniel/movietv.wav
sound/barniel/nosir.wav
sound/barniel/notatall.wav
sound/barniel/openfire.wav
sound/barniel/rightway.wav
sound/barniel/seelater.wav
sound/barniel/seeya.wav
sound/barniel/seeyoulater.wav
sound/barniel/somethingmoves.wav
sound/barniel/teamup1.wav
sound/barniel/teamup2.wav
sound/barniel/thinking.wav
sound/barniel/whatsgoingon.wav
sound/barniel/yesbarn.wav
sound/barniel/yessir.wav
sound/barniel/youneedmedic.wav
sound/gargfoot/whistle.wav
sound/richard_boderman/boderman_defeat.ogg
sound/richard_boderman/boderman_speaker1.ogg
sound/richard_boderman/boderman_speaker2.ogg
sound/richard_boderman/boderman_speaker3.ogg
sound/richard_boderman/huey_rotor.wav
sound/richard_boderman/hueytimer1.wav
sound/richard_boderman/hueytimer2.wav
sound/richard_boderman/hueytimer3.wav
sound/richard_boderman/wagner.mp3
sound/richard_boderman/wagnerboss.ogg
sound/shl/m41a_3round.wav
sound/wheelchair/wheelchair_jog.wav
sound/wheelchair/wheelchair_walk.wav
