// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
models/sa13/agrunt.mdl
models/sa13/agruntf.mdl
models/sa13/agruntf01.mdl
models/sa13/agruntfT.mdl
models/sa13/apache.mdl
models/sa13/apachet.mdl
models/sa13/baby_voltigore.mdl
models/sa13/bd.mdl
models/sa13/big_mom.mdl
models/sa13/big_momt.mdl
models/sa13/bullsquid.mdl
models/sa13/bullsquid01.mdl
models/sa13/bullsquidt.mdl
models/sa13/controller.mdl
models/sa13/controllerT.mdl
models/sa13/garg.mdl
models/sa13/gargT.mdl
models/sa13/gevaudan.mdl
models/sa13/grenade.mdl
models/sa13/headcrab.mdl
models/sa13/hgrunt.mdl
models/sa13/hgrunt01.mdl
models/sa13/hgrunt02.mdl
models/sa13/hgrunt03.mdl
models/sa13/hgruntT.mdl
models/sa13/houndeye.mdl
models/sa13/houndeyet.mdl
models/sa13/hwgrunt.mdl
models/sa13/hyshell.mdl
models/sa13/icky.mdl
models/sa13/ickyt.mdl
models/sa13/islave.mdl
models/sa13/islave01.mdl
models/sa13/islave02.mdl
models/sa13/islavet.mdl
models/sa13/massn.mdl
models/sa13/ngapache.mdl
models/sa13/ngapacheT.mdl
models/sa13/ngt_boys.mdl
models/sa13/p_9mmhandgun.mdl
models/sa13/p_akm.mdl
models/sa13/p_crowbar.mdl
models/sa13/p_de.mdl
models/sa13/p_gtc.mdl
models/sa13/p_hegrenade.mdl
models/sa13/p_kurst.mdl
models/sa13/p_medkit.mdl
models/sa13/p_minigun.mdl
models/sa13/p_python.mdl
models/sa13/p_rop.mdl
models/sa13/p_rpg.mdl
models/sa13/p_sg550.mdl
models/sa13/p_shotgun.mdl
models/sa13/p_sniper.mdl
models/sa13/p_stoner.mdl
models/sa13/panchem.mdl
models/sa13/perche.mdl
models/sa13/pit_drone.mdl
models/sa13/ru.mdl
models/sa13/ru2.mdl
models/sa13/sas.mdl
models/sa13/shotgunshell.mdl
models/sa13/strooper.mdl
models/sa13/strooper01.mdl
models/sa13/strooper_gibs.mdl
models/sa13/stukabat.mdl
models/sa13/stukabatT.mdl
models/sa13/tentacle2.mdl
models/sa13/tentacle2t.mdl
models/sa13/tropical.mdl
models/sa13/v_9mm.mdl
models/sa13/v_akm.mdl
models/sa13/v_awp.mdl
models/sa13/v_crowbar.mdl
models/sa13/v_de.mdl
models/sa13/v_gn.mdl
models/sa13/v_hegrenade.mdl
models/sa13/v_kurst.mdl
models/sa13/v_m3.mdl
models/sa13/v_medkit.mdl
models/sa13/v_minigun.mdl
models/sa13/v_python.mdl
models/sa13/v_rop.mdl
models/sa13/v_rpg.mdl
models/sa13/v_satchel.mdl
models/sa13/v_satchel_radio.mdl
models/sa13/v_sg550.mdl
models/sa13/v_smag.mdl
models/sa13/v_stoner.mdl
models/sa13/v_tfc_sniper.mdl
models/sa13/v_tripmine.mdl
models/sa13/w_357ammobox.mdl
models/sa13/w_9mmARclip.mdl
models/sa13/w_9mmbox.mdl
models/sa13/w_9mmboxt.mdl
models/sa13/w_9mmclip.mdl
models/sa13/w_9mmhandgun.mdl
models/sa13/w_akm.mdl
models/sa13/w_ammo_556.mdl
models/sa13/w_ammo_rop.mdl
models/sa13/w_ARgrenade.mdl
models/sa13/w_crossbow_clip.mdl
models/sa13/w_crowbar.mdl
models/sa13/w_de.mdl
models/sa13/w_gtc.mdl
models/sa13/w_hegrenade.mdl
models/sa13/w_kurst.mdl
models/sa13/w_m3.mdl
models/sa13/w_minigun.mdl
models/sa13/w_python.mdl
models/sa13/w_rop.mdl
models/sa13/w_ropT.mdl
models/sa13/w_rpg.mdl
models/sa13/w_rpgammo.mdl
models/sa13/w_rpgT.mdl
models/sa13/w_satchel.mdl
models/sa13/w_satchelT.mdl
models/sa13/w_sg550.mdl
models/sa13/w_sniper.mdl
models/sa13/w_spas.mdl
models/sa13/w_stoner.mdl
models/sa13/zombie.mdl
models/sa13/zombie01.mdl
models/sa13/zombie02.mdl
models/sa13/zombie03.mdl
models/sa13/zombie04.mdl
sound/sa13/ambience/alarmeu.WAV
sound/sa13/ambience/alrm6.wav
sound/sa13/ambience/alrm7.wav
sound/sa13/ambience/alrm8.wav
sound/sa13/ambience/alrm9.wav
sound/sa13/ambience/alrme5.wav
sound/sa13/ambience/Birds1.wav
sound/sa13/ambience/Birds10.WAV
sound/sa13/ambience/Birds11.wav
sound/sa13/ambience/Birds2.wav
sound/sa13/ambience/Birds3.wav
sound/sa13/ambience/Birds4.wav
sound/sa13/ambience/Birds5.wav
sound/sa13/ambience/Birds6.wav
sound/sa13/ambience/Birds7.wav
sound/sa13/ambience/Birds8.wav
sound/sa13/ambience/Birds9.wav
sound/sa13/ambience/faucon.WAV
sound/sa13/ambience/faucon2.wav
sound/sa13/ambience/frog.WAV
sound/sa13/ambience/frog2.WAV
sound/sa13/ambience/h2.wav
sound/sa13/ambience/lan1shut.wav
sound/sa13/ambience/machines.WAV
sound/sa13/ambience/machines3.WAV
sound/sa13/ambience/sewer1.wav
sound/sa13/ambience/turbine.WAV
sound/sa13/ambience/VENTA.wav
sound/sa13/ambience/VENTB.wav
sound/sa13/ambience/VENTC.wav
sound/sa13/ambience/VENTD.wav
sound/sa13/ambience/water1.WAV
sound/sa13/hassault/hw_gun4.wav
sound/sa13/hassault/hw_shoot2.wav
sound/sa13/hassault/hw_shoot3.wav
sound/sa13/hassault/hw_spin.wav
sound/sa13/hassault/hw_spindown.wav
sound/sa13/hassault/hw_spinup.wav
sound/sa13/pitdrone/pit_drone_alert1.wav
sound/sa13/pitdrone/pit_drone_alert2.wav
sound/sa13/pitdrone/pit_drone_alert3.wav
sound/sa13/pitdrone/pit_drone_die1.wav
sound/sa13/pitdrone/pit_drone_die2.wav
sound/sa13/pitdrone/pit_drone_die3.wav
sound/sa13/pitdrone/pit_drone_eat.wav
sound/sa13/shocktrooper/shock_fire.wav
sound/sa13/shocktrooper/shock_trooper_attack.wav
sound/sa13/voltigore/voltigore_attack_melee2.wav
sound/sa13/voltigore/voltigore_attack_shock.wav
sound/sa13/voltigore/voltigore_idle1.wav
sound/sa13/weapons/357_reload1.wav
sound/sa13/weapons/357_shot1.wav
sound/sa13/weapons/357_shot2.wav
sound/sa13/weapons/explode4.WAV
sound/sa13/weapons/gauss2.wav
sound/sa13/weapons/hks1.wav
sound/sa13/weapons/hks2.wav
sound/sa13/weapons/hks3.wav
sound/sa13/weapons/pl_gun3.wav
sound/sa13/weapons/reload1.wav
sound/sa13/weapons/reload2.wav
sound/sa13/weapons/reload3.wav
sound/sa13/weapons/ric1.wav
sound/sa13/weapons/ric2.wav
sound/sa13/weapons/ric3.wav
sound/sa13/weapons/ric4.wav
sound/sa13/weapons/ric5.wav
sound/sa13/weapons/ric6.wav
sound/sa13/weapons/rocketfire1.wav
sound/sa13/weapons/saw_fire1.wav
sound/sa13/weapons/saw_fire2.wav
sound/sa13/weapons/saw_fire3.wav
sound/sa13/weapons/saw_reload.wav
sound/sa13/weapons/saw_reload2.wav
sound/sa13/weapons/sbarrel1.wav
sound/sa13/weapons/sniper_bolt1.wav
sound/sa13/weapons/sniper_bolt2.wav
sound/sa13/weapons/sniper_fire.wav
sound/sa13/weapons/sniper_fire_last _round.WAV
sound/sa13/weapons/sniper_miss.wav
sound/sa13/weapons/sniper_reload3.wav
sound/sa13/weapons/sniper_reload_first_seq.wav
sound/sa13/weapons/sniper_reload_second_seq.wav
sound/sa13/weapons/sniper_zoom.wav
sound/sa13/weapons/sshell1.wav
sound/sa13/weapons/sshell2.wav
sound/sa13/weapons/sshell3.wav
sound/sa13/weapons/uzi/fire_both1.wav
sound/sa13/weapons/uzi/fire_both2.wav
sound/sa13/weapons/uzi/reload1.wav
sound/sa13/weapons/uzi/reload2.wav
sound/sa13/weapons/uzi/reload3.wav
sound/sa13/weapons/uzi/reload_left1.wav
sound/sa13/weapons/uzi/reload_left2.wav
sound/sa13/weapons/uzi/reload_right1.wav
sound/sa13/weapons/uzi/reload_right2.wav
sound/sa13/weapons/uzi/shoot1.wav
sound/sa13/weapons/uzi/shoot2.wav
sound/sa13/weapons/uzi/shoot3.wav
sound/sa13/weapons/xbow_fire1.wav
sound/sa13/weapons/xbow_fly1.wav
sound/sa13/weapons/xbow_hit1.wav
sound/sa13/weapons/xbow_hit2.wav
sound/sa13/weapons/xbow_reload1.wav
sound/sa13/zombie/zo_alert10.wav
sound/sa13/zombie/zo_alert20.wav
sound/sa13/zombie/zo_attack1.wav
sound/sa13/zombie/zo_idle1.wav
sound/sa13/zombie/zo_idle2.wav
sound/sa13/zombie/zo_idle3.wav
sound/sa13/zombie/zo_idle4.wav
sound/sa13/zombie/zo_pain1.wav
sound/weapons/1-2-5-3.wav
sound/weapons/629_shells_land.wav
sound/weapons/ak100_magin.wav
sound/weapons/ak100_magout.wav
sound/weapons/ak100_safety.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sprites/sa13/3dm_palm_01.spr
sprites/sa13/3dm_palm_02.spr
sprites/sa13/3dm_palm_03.spr
sprites/sa13/ghostfish5.spr
sprites/sa13/nm_tree2.spr
sprites/sa13/nm_tree6.spr
sprites/sa13/pine2.spr
sprites/sa13/thwtree1.spr
