// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

models/death_mission/aplant1.mdl
models/death_mission/aplant2.mdl
models/death_mission/arc_fern.mdl
models/death_mission/bonez.mdl
models/death_mission/c_headcrab.mdl
models/death_mission/eaten1.mdl
models/death_mission/gib_hgrunt.mdl
models/death_mission/headcrab.mdl
models/death_mission/hgibs.mdl
models/death_mission/monsters/archvile.mdl
models/death_mission/monsters/licker.mdl
models/death_mission/monsters/omfg_rusty.mdl
models/death_mission/monsters/pit_drone.mdl
models/death_mission/monsters/superlicker.mdl
models/death_mission/tree1.mdl
models/death_mission/xen_tree5.mdl
models/death_mission/zombies/zombie.mdl
models/death_mission/zombies/zombie01.mdl
models/death_mission/zombies/zombie02.mdl
models/death_mission/zombies/zombie03.mdl
models/death_mission/zombies/zombie2.mdl
models/death_mission/zombies/zombie_h.mdl
models/death_mission/zombies/zombie_sc2.mdl
sound/death_mission/burning1.wav
sound/death_mission/computalk2.wav
sound/death_mission/drips.wav
sound/death_mission/fan1.wav
sound/death_mission/mechwhine.wav
sound/death_mission/monster2.wav
sound/death_mission/mwalk.wav
sound/death_mission/squitch.wav
sound/death_mission/suspense01.wav
sound/death_mission/wind2.wav
sound/death_mission/zg1.wav
sound/death_mission/zo_moan3.wav
sprites/death_mission/e-tele1.spr
sprites/death_mission/fire.spr
