// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

models/death_mission/abone_template1.mdl
models/death_mission/aplant1.mdl
models/death_mission/aplant2.mdl
models/death_mission/aplant3.mdl
models/death_mission/aplant4.mdl
models/death_mission/arc_fern.mdl
models/death_mission/bigrat.mdl
models/death_mission/bonez.mdl
models/death_mission/c_headcrab.mdl
models/death_mission/civilian.mdl
models/death_mission/eaten1.mdl
models/death_mission/eaten3.mdl
models/death_mission/gib_hgrunt.mdl
models/death_mission/hgibs.mdl
models/death_mission/monsters/archvile.mdl
models/death_mission/monsters/icky.mdl
models/death_mission/monsters/ickyt.mdl
models/death_mission/monsters/kcobra.mdl
models/death_mission/monsters/licker.mdl
models/death_mission/monsters/mutant_shark.mdl
models/death_mission/monsters/mutant_sharkt.mdl
models/death_mission/monsters/panther.mdl
models/death_mission/monsters/superlicker.mdl
models/death_mission/tree1.mdl
models/death_mission/tree3.mdl
models/death_mission/xen_tree5.mdl
models/death_mission/xen_treebark.mdl
models/death_mission/zombies/zombie2/zombie.mdl
models/death_mission/zombies/zombie2/zombieT.mdl
models/death_mission/zombies/zombie_h.mdl
models/death_mission/zombies/zombie_sc2.mdl
models/death_mission/zombies/zombie_soldier.mdl
sound/death_mission/claw2.wav
sound/death_mission/crickets.wav
sound/death_mission/mine_deploy.wav
sound/death_mission/monster2.wav
sound/death_mission/squitch.wav
sound/death_mission/theme1.wav
sound/death_mission/waterfall3.wav
sound/death_mission/wind2.wav
sprites/death_mission/e-tele1.spr
sprites/death_mission/fire.spr
sprites/death_mission/glow01.spr
sprites/death_mission/stmbal1.spr
